import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/ui/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text:black dark:text-slate-100 bg-white dark:bg-slate-900">
        <Container>{children}</Container>
      </body>
    </html>
  );
}
